spring:
  security:
    oauth2:
      authorization-server:
        issuer-uri: http://127.0.0.1:8080
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/auth-server?serverTimezone=UTC&userUnicode=true&characterEncoding=utf-8
    username: root
    password: root
  data:
    redis:
      host: 192.168.98.131
      port: 6379
      database: 0
      timeout: 1800000
      password: '000214'
      jedis:
        pool:
          max-active: 20 #最大连接数
          max-wait: -1    #最大阻塞等待时间(负数表示没限制)
          max-idle: 5    #最大空闲
          min-idle: 0     #最小空闲
logging:
  level:
    org.springframework.security: debug
custom:
  # 自定义认证配置
  security:
    # 不需要认证的地址
    ignore-uri-list: assets/**, /webjars/**, /login, /getCaptcha, /getSmsCaptcha, /error, /oauth2/consent/parameters, /qrCode/login/**
    # 当前认证服务访问的路径
    issuer-url: http://127.0.0.1:8080
    login-url: http://127.0.0.1:5173/login