### 获取 Token
POST http://localhost:8000/oauth2/token
Content-Type: application/x-www-form-urlencoded
Authorization: Basic Y2xpZW50LWlkOmNsaWVudC1zZWNyZXQ=

grant_type=client_credentials

###  令牌校验
POST http://localhost:9000/oauth2/introspect
Content-Type: application/x-www-form-urlencoded
Authorization: Basic Y2xpZW50LWlkOmNsaWVudC1zZWNyZXQ=

token=eyJraWQiOiI3NDAxNWJiNC04YTNiLTQwN2UtYTA3YS1hYjY2YzFhNTlmZGQiLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJjbGllbnQtaWQiLCJhdWQiOiJjbGllbnQtaWQiLCJuYmYiOjE3MzQyNzUyNDYsImlzcyI6Imh0dHA6Ly9sb2NhbGhvc3Q6OTAwMCIsImV4cCI6MTczNDI3NTU0NiwiaWF0IjoxNzM0Mjc1MjQ2LCJqdGkiOiI3YjM5NTczMC04NzVmLTQ0ZWYtOWJiZi0yN2IxNGE3ZjQ2ODcifQ.LT_eTBtJJKffoR_NPyGvr5GZdrzHR71OyVAw8mKvZlv2jIeO8cSoWXNkivrO1TqMtZq1e11ElAqsqdHNPx6jiLR_aGiDuSwY7TvQC1f4joahfYS2S0F3Up5ZXg72Z5N_VQteXXGqMyHmcY3bnZMZ-jHL_WTq3uvXgiqXt64kR3vMZso7aut9UV4AhkHaTRnxGJjs2Qp8eVOvSx13LoiLSML4031EEnRqqtLC-vNCR9z5PJ0X766EHeJtQhbgx-3mVuY0AtwV3tqSX9PdAFh8cSJXhkqz9BLM1lqxL0_PpfzTT4LNJaZKEt0aFImPd9IC6UmK80xtJBiQqY_79lWsHg